package com.example.Studentlibrarymanagement.Services;

import com.example.Studentlibrarymanagement.Enums.CardStatus;
import com.example.Studentlibrarymanagement.Models.Card;
import com.example.Studentlibrarymanagement.Models.Student;
import com.example.Studentlibrarymanagement.Repositories.StudentRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

@Service
public class StudentService {

    @Autowired
    StudentRepository studentRepository;
    public String createStudent(Student student){

        //Student ,from the postman is already having the basic attribute set.


        //card should be autogenerated when createStudent function is called.
        Card card = new Card();
        card.setCardStatus(CardStatus.BLOCKED);
        card.setStudent(student);

        //lets go to the student
        student.setCard(card);

        //if there was a unidirectional mapping : we had to save both of them

        //But we are super advanced and are using bidirectional mapping. In bidirectional mapping
        //child will automatically be saved.

        studentRepository.save(student);

        //By cascading effect,child will automatically be saved.

        return "Student and card added";
    }
}
